# These are supported funding model platforms

patreon: CraftRBLX Productions
custom: ["https://www.youtube.com/channel/UCEh6ZxENe-OzEu_tl3t3s-w?", "https://craftrblx.github.io", "CraftRBLX Productions"]
